export const GET_CUSTOMER = 'GET_CUSTOMER';
export const SAVE_CUSTOMER = 'SAVE_CUSTOMER'
export const CHANGE_CUSTOMER_STATUS = 'CHANGE_CUSTOMER_STATUS';
export const GET_CUSTOMER_PATIENT = 'GET_CUSTOMER_PATIENT';
export const SAVE_CUSTOMER_PATIENT = 'SAVE_CUSTOMER_PATIENT'