export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESSFUL = 'EDIT_PROFILE_SUCCESSFUL';
export const EDIT_AVATAR = 'EDIT_AVATAR';
export const EDIT_AVATAR_SUCCESSFUL = 'EDIT_AVATAR_SUCCESSFUL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESSFUL = 'CHANGE_PASSWORD_SUCCESSFUL';
export const SET_STATUS = 'SET_STATUS';

export const FORGOT_PASSWORD_SEND_MAIL = 'FORGOT_PASSWORD_SEND_MAIL';
export const FORGOT_PASSWORD_SEND_MAIL_SUCCESSFUL = 'FORGOT_PASSWORD_SEND_MAIL_SUCCESSFUL';
export const FORGOT_PASSWORD_SEND_PASSWORD = 'FORGOT_PASSWORD_SEND_PASSWORD';
export const FORGOT_PASSWORD_SEND_PASSWORD_SUCCESSFUL = 'FORGOT_PASSWORD_SEND_PASSWORD_SUCCESSFUL';
export const CHECK_EMAIL_EXPIRED = 'CHECK_EMAIL_EXPIRED';
export const CHECK_EMAIL_EXPIRED_SUCCESSFUL = 'CHECK_EMAIL_EXPIRED_SUCCESSFUL';

export const GET_DOCTOR = 'GET_DOCTOR';
export const GET_DOCTOR_SUCCESSFUL = 'GET_DOCTOR_SUCCESSFUL';
export const CREATE_DOCTOR = 'CREATE_DOCTOR';
export const CREATE_DOCTOR_SUCCESSFUL = 'CREATE_DOCTOR_SUCCESSFUL';
export const UPDATE_DOCTOR = 'UPDATE_DOCTOR';
export const UPDATE_DOCTOR_SUCCESSFUL = 'UPDATE_DOCTOR_SUCCESSFUL';