export const EDIT_PROFILE = "EDIT_PROFILE";
export const EDIT_PROFILE_SUCCESSFUL = "EDIT_PROFILE_SUCCESSFUL";
export const EDIT_AVATAR = "EDIT_AVATAR";
export const EDIT_AVATAR_SUCCESSFUL = "EDIT_AVATAR_SUCCESSFUL";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESSFUL = "CHANGE_PASSWORD_SUCCESSFUL";
export const SET_STATUS = "SET_STATUS";

export const FORGOT_PASSWORD_SEND_MAIL = "FORGOT_PASSWORD_SEND_MAIL";
export const FORGOT_PASSWORD_SEND_MAIL_SUCCESSFUL = "FORGOT_PASSWORD_SEND_MAIL_SUCCESSFUL";
export const FORGOT_PASSWORD_SEND_PASSWORD = "FORGOT_PASSWORD_SEND_PASSWORD";
export const FORGOT_PASSWORD_SEND_PASSWORD_SUCCESSFUL = "FORGOT_PASSWORD_SEND_PASSWORD_SUCCESSFUL";
export const CHECK_EMAIL_EXPIRED = "CHECK_EMAIL_EXPIRED";
export const CHECK_EMAIL_EXPIRED_SUCCESSFUL = "CHECK_EMAIL_EXPIRED_SUCCESSFUL";

export const GET_DOCTOR = "GET_DOCTOR";
export const GET_DOCTOR_SUCCESSFUL = "GET_DOCTOR_SUCCESSFUL";
export const CREATE_DOCTOR = "CREATE_DOCTOR";
export const CREATE_DOCTOR_SUCCESSFUL = "CREATE_DOCTOR_SUCCESSFUL";
export const UPDATE_DOCTOR = "UPDATE_DOCTOR";
export const UPDATE_DOCTOR_SUCCESSFUL = "UPDATE_DOCTOR_SUCCESSFUL";

export const CHANGE_DOCTOR_STATUS = "CHANGE_DOCTOR_STATUS";
export const CHANGE_DOCTOR_STATUS_SUCCESSFUL = "CHANGE_DOCTOR_STATUS_SUCCESSFUL";

export const GET_DOCTOR_EXPERIENCE = "GET_DOCTOR_EXPERIENCE";
export const GET_DOCTOR_EXPERIENCE_SUCCESSFUL = "GET_DOCTOR_EXPERIENCE_SUCCESSFUL";
export const UPDATE_DOCTOR_EXPERIENCE = "UPDATE_DOCTOR_EXPERIENCE";
export const UPDATE_DOCTOR_EXPERIENCE_SUCCESSFUL = "UPDATE_DOCTOR_EXPERIENCE_SUCCESSFUL";

export const GET_DOCTOR_LANGUAGE = "GET_DOCTOR_LANGUAGE";
export const GET_DOCTOR_LANGUAGE_SUCCESSFUL = "GET_DOCTOR_LANGUAGE_SUCCESSFUL";
export const UPDATE_DOCTOR_LANGUAGE = "UPDATE_DOCTOR_LANGUAGE";
export const UPDATE_DOCTOR_LANGUAGE_SUCCESSFUL = "UPDATE_DOCTOR_LANGUAGE_SUCCESSFUL";

export const GET_DOCTOR_DEGREE = "GET_DOCTOR_DEGREE";
export const GET_DOCTOR_DEGREE_SUCCESSFUL = "GET_DOCTOR_DEGREE_SUCCESSFUL";
export const UPDATE_DOCTOR_DEGREE = "UPDATE_DOCTOR_DEGREE";
export const UPDATE_DOCTOR_DEGREE_SUCCESSFUL = "UPDATE_DOCTOR_DEGREE_SUCCESSFUL";

export const GET_ALL_LANGUAGE = "GET_ALL_LANGUAGE";
export const GET_ALL_LANGUAGE_SUCCESSFUL = "GET_ALL_LANGUAGE_SUCCESSFUL";
export const CREATE_LANGUAGE = "CREATE_LANGUAGE";
export const CREATE_LANGUAGE_SUCCESSFUL = "CREATE_LANGUAGE_SUCCESSFUL";
export const UPDATE_LANGUAGE = "UPDATE_LANGUAGE";
export const UPDATE_LANGUAGE_SUCCESSFUL = "UPDATE_LANGUAGE_SUCCESSFUL";
export const DELETE_LANGUAGE = "DELETE_LANGUAGE";

export const GET_ALL_DEGREE = "GET_ALL_DEGREE";
export const GET_ALL_DEGREE_SUCCESSFUL = "GET_ALL_DEGREE_SUCCESSFUL";
export const CREATE_DEGREE = "CREATE_DEGREE";
export const CREATE_DEGREE_SUCCESSFUL = "CREATE_DEGREE_SUCCESSFUL";
export const UPDATE_DEGREE = "UPDATE_DEGREE";
export const UPDATE_DEGREE_SUCCESSFUL = "UPDATE_DEGREE_SUCCESSFUL";
export const DELETE_DEGREE = "DELETE_DEGREE";
