export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESSFUL = 'EDIT_PROFILE_SUCCESSFUL';
export const EDIT_AVATAR = 'EDIT_AVATAR';
export const EDIT_AVATAR_SUCCESSFUL = 'EDIT_AVATAR_SUCCESSFUL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESSFUL = 'CHANGE_PASSWORD_SUCCESSFUL';
export const SET_STATUS = 'SET_STATUS';

export const FORGOT_PASSWORD_SEND_MAIL = 'FORGOT_PASSWORD_SEND_MAIL';
export const FORGOT_PASSWORD_SEND_MAIL_SUCCESSFUL = 'FORGOT_PASSWORD_SEND_MAIL_SUCCESSFUL';
export const FORGOT_PASSWORD_SEND_PASSWORD = 'FORGOT_PASSWORD_SEND_PASSWORD';
export const FORGOT_PASSWORD_SEND_PASSWORD_SUCCESSFUL = 'FORGOT_PASSWORD_SEND_PASSWORD_SUCCESSFUL';
export const CHECK_EMAIL_EXPIRED = 'CHECK_EMAIL_EXPIRED';
export const CHECK_EMAIL_EXPIRED_SUCCESSFUL = 'CHECK_EMAIL_EXPIRED_SUCCESSFUL';