export const SET_CURRENT_SERVICE_PAGE = 'SET_CURRENT_SERVICE_PAGE';
export const GET_SERVICE = 'GET_SERVICE';
export const SAVE_SERVICE = 'SAVE_SERVICE';
export const ADD_SERVICE = 'ADD_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const GET_SERVICE_CATEGORY = 'GET_SERVICE_CATEGORY';
export const SAVE_SERVICE_CATEGORY = 'SAVE_SERVICE_CATEGORY';
export const ADD_SERVICE_CATEGORY  = 'ADD_SERVICE_CATEGORY';