export const GET_TOP_DOCTOR = 'GET_TOP_DOCTOR';
export const GET_TOP_DOCTOR_SUCCESSFUL = 'GET_TOP_DOCTOR_SUCCESSFUL';
export const GET_STATISTIC_DATA_APMPKG = 'GET_STATISTIC_DATA_APMPKG';
export const GET_STATISTIC_DATA_APMPKG_SUCCESSFUL = 'GET_STATISTIC_DATA_APMPKG_SUCCESSFUL';
